dataset: 'nicapotato/womens-ecommerce-clothing-reviews'
raw_path: 'data/raw'
raw_data: 'Womens Clothing E-Commerce Reviews.csv'
target: 'recommended_ind'
variables:
  - 'clothing_id'
  - 'review_text'
random_state: 8
test_size: 0.2
val_size: 0.25
interim_path: 'data/interim'
interim_data:
  - 'train.csv'
  - 'test.csv'
  - 'val.csv'
lang: 'english'
text: 'review_text'
text-processed: 'review_text_processed'
processed_path: 'data/processed'