interim_path: 'data/interim'
interim_data:
  - 'train.csv'
  - 'test.csv'
  - 'val.csv'
random_state: 8
lang: 'english'
text: 'review_text'
text-processed: 'review_text_processed'
processed_path: 'data/processed'
processed_data:
  - 'train_processed.csv'
  - 'test_processed.csv'
  - 'val_processed.csv'